services:
  aiostreams:
    build:
      context: https://github.com/anks-mrangry/AIOStreams.git#main
      dockerfile: Dockerfile  # optional if your Dockerfile is named differently or in subfolder
      args:
        # Optional: pass any build arguments if needed
    container_name: aiostreams
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    healthcheck:
      test: wget -qO- http://localhost:3000/api/v1/status
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s
